// Regenerates utils/icons.ts: the inline SVG path data behind <Icon>.
//
// Icons are compiled into the bundle instead of being fetched from the Iconify
// API at runtime, so they are present in the prerendered HTML (no pop-in, no
// extra network requests, nothing for a crawler to miss).
//
// To add an icon: append its Phosphor name to ICONS, then run
//   node scripts/build-icons.mjs
// Browse names at https://phosphoricons.com (regular weight, or "-fill").
import { writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const ICONS = [
  'arrow-clockwise',
  'arrow-down',
  'arrow-left',
  'arrow-right',
  'arrow-square-out',
  'arrow-up',
  'arrow-up-right',
  'brain',
  'calendar-check',
  'check',
  'check-circle',
  'cookie',
  'devices',
  'download-simple',
  'envelope-simple',
  'file-text',
  'github-logo',
  'list',
  'linkedin-logo',
  'list-bullets',
  'lock-simple',
  'moon',
  'plugs-connected',
  'printer',
  'prohibit',
  'skype-logo',
  'star-fill',
  'sun',
  'whatsapp-logo',
  'x',
  'x-circle',
]

const out = resolve(dirname(fileURLToPath(import.meta.url)), '../utils/icons.ts')
const res = await fetch(`https://api.iconify.design/ph.json?icons=${ICONS.join(',')}`)
if (!res.ok) throw new Error(`Iconify responded ${res.status}`)
const data = await res.json()

const missing = ICONS.filter((name) => !data.icons[name])
if (missing.length) throw new Error(`Unknown Phosphor icons: ${missing.join(', ')}`)

const entries = ICONS.map((name) => {
  const body = data.icons[name].body
  const paths = [...body.matchAll(/\sd="([^"]+)"/g)].map((m) => m[1])
  if (paths.length !== 1) throw new Error(`${name}: expected a single <path>, got ${paths.length}`)
  return `  '${name}': '${paths[0]}',`
})

const file = `// GENERATED by scripts/build-icons.mjs. Do not edit by hand.
// Phosphor Icons (MIT, see THIRD_PARTY_NOTICES.md), regular weight, 256x256 viewBox, single path each.
export const iconPaths: Record<string, string> = {
${entries.join('\n')}
}
`
await writeFile(out, file)
console.log(`Wrote ${ICONS.length} icons to utils/icons.ts (${(file.length / 1024).toFixed(1)} KB)`)
